nucleus_driver:
  ros__parameters:
    # Descriptions for all DVL configurations can be found in the Nucleus
    # documentation

    # Default IP address for the Nucleus DVL when used with the BlueROV2.
    ip_address: "192.168.2.201"

    # Default password for the DVL.
    password: "nortek"

    # Specify a timeout for the DVL connection.
    timeout: 5 # seconds

    # Specify the maximum number of connection attempts made during
    # configuration. Set to -1 to retry indefinitely.
    max_retries: -1

    # Specify the delay between DVL connection attempts.
    retry_interval: 5.0 # seconds

    # The INS inertial frame is defined using the "North-East-Down" orientation positioned
    # at the point where the "start measurement" command is issued.
    frame_id: "odom_ned"

    # All measurements are obtained from the DVL use the following coordinate
    # convention:
    # - x: Forward
    # - y: Right
    # - z: Down
    child_frame_id: "dvl_link"
