#pragma once

#include <rclcpp_components/register_node_macro.hpp>
#include <rclcpp_lifecycle/lifecycle_node.hpp>
#include <sensor_msgs/msg/imu.hpp>

#include "client.hpp"

// auto-generated by generate_parameter_library
#include <autonomy_teensy/teensy_driver_parameters.hpp>

namespace teensy
{

using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;

class TeensyDriver : public rclcpp_lifecycle::LifecycleNode
{
public:
  explicit TeensyDriver(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

  ~TeensyDriver() override;

  auto on_configure(const rclcpp_lifecycle::State & previous_state) -> CallbackReturn override;

  auto on_activate(const rclcpp_lifecycle::State & previous_state) -> CallbackReturn override;

  auto on_deactivate(const rclcpp_lifecycle::State & previous_state) -> CallbackReturn override;

  auto on_cleanup(const rclcpp_lifecycle::State & previous_state) -> CallbackReturn override;

private:
  std::unique_ptr<protocol::Client> client_;

  std::shared_ptr<teensy_driver::ParamListener> param_listener_;
  teensy_driver::Params params_;

  rclcpp_lifecycle::LifecyclePublisher<sensor_msgs::msg::Imu>::SharedPtr imu_pub_;
};

}  // namespace teensy

RCLCPP_COMPONENTS_REGISTER_NODE(teensy::TeensyDriver)
