#pragma once

#include <array>
#include <autonomy_msgs/msg/imu_calibration_status.hpp>
#include <cstdint>
#include <future>
#include <mutex>
#include <optional>
#include <rclcpp_components/register_node_macro.hpp>
#include <rclcpp_lifecycle/lifecycle_node.hpp>
#include <sensor_msgs/msg/imu.hpp>
#include <std_srvs/srv/trigger.hpp>
#include <string>

#include "client.hpp"
#include "command.hpp"

// auto-generated by generate_parameter_library
#include <autonomy_teensy/teensy_driver_parameters.hpp>

namespace teensy
{

using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;

class TeensyDriver : public rclcpp_lifecycle::LifecycleNode
{
public:
  explicit TeensyDriver(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

  ~TeensyDriver() override;

  auto on_configure(const rclcpp_lifecycle::State & previous_state) -> CallbackReturn override;

  auto on_activate(const rclcpp_lifecycle::State & previous_state) -> CallbackReturn override;

  auto on_deactivate(const rclcpp_lifecycle::State & previous_state) -> CallbackReturn override;

  auto on_cleanup(const rclcpp_lifecycle::State & previous_state) -> CallbackReturn override;

private:
  auto send_command(protocol::CommandId command_id, std::uint8_t arg, std::string & message) -> bool;

  std::unique_ptr<protocol::Client> client_;

  std::shared_ptr<teensy_driver::ParamListener> param_listener_;
  teensy_driver::Params params_;

  rclcpp_lifecycle::LifecyclePublisher<sensor_msgs::msg::Imu>::SharedPtr imu_pub_;

  rclcpp::Publisher<autonomy_msgs::msg::ImuCalibrationStatus>::SharedPtr calib_pub_;

  rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr start_cal_srv_;
  rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr save_cal_srv_;
  rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr stop_cal_srv_;

  // we only handle one command at a time; otherwise, I would use a map/vector here.
  std::mutex command_lock_;
  std::optional<std::promise<std::array<std::uint8_t, 3>>> pending_promise_;
  std::uint8_t pending_seq_{0};
  std::uint8_t command_seq_{0};
};

}  // namespace teensy

RCLCPP_COMPONENTS_REGISTER_NODE(teensy::TeensyDriver)
