services:
  ros:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    network_mode: host
    volumes:
      - type: bind
        source: ../
        target: /home/ubuntu/ws_ros/src/bluerov-pi
    # uncomment the following for interactive mode
    command: tail -f /dev/null

  mavros:
    extends: ros
    command: ros2 launch bluerov_bringup bluerov.launch.yaml
