# Copyright 2025, Evan Palmer
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

from struct import pack, unpack
from typing import Any

import rclpy

# auto-generated by generate_parameter_library_py
from autonomy_routers.bar30_parameters import bar30_interface
from geometry_msgs.msg import PoseWithCovarianceStamped
from mavros_msgs.msg import Mavlink
from rclpy.node import Node
from rclpy.qos import qos_profile_system_default as qos


class Bar30Router(Node):
    """Converts pressure data received from the Bar 30 sensor into depth estimates."""

    def __init__(self):
        super().__init__("bar30_router")

        self.param_listener = bar30_interface.ParamListener(self)
        self.params = self.param_listener.get_params()

        self.mavlink_sub = self.create_subscription(
            Mavlink, self.params.incoming_topic, self.route_depth_cb, qos
        )

        self.depth_pub = self.create_publisher(
            PoseWithCovarianceStamped, self.params.outgoing_topic, qos
        )

    def route_depth_cb(self, data: Mavlink):
        # filter the messages to get the SCALED_PRESSURE2 messages (ID 137)
        # see https://mavlink.io/en/messages/common.html for more information
        if data.msgid != 137:
            return

        # convert the raw message into a pressure reading
        # returns time_boot_ms, press_abs, press_diff, temp
        p = pack("QQ", *data.payload64)
        _, press_abs, _, _ = unpack("Iffhxx", p)

        atm_press = 101325  # atmospheric pressure (Pa)
        g = -9.80665  # gravity points down for the EKF

        # depth can be calculated from the following:
        # P = rho * g * h,
        # where P is the pressure, rho is the fluid density, g is gravity, and h is
        # depth.
        depth = (press_abs * 100 - atm_press) / self.params.fluid_density / g

        # the MS5837-30BA datasheet lists the RMS resolution as 0.2 mbar for the default
        # settings. estimate the covariance from this measurement
        cov = ((0.2 * 100) ** 2) / self.params.fluid_density / -g

        msg = PoseWithCovarianceStamped()
        msg.header.stamp = data.header.stamp
        msg.header.frame_id = self.params.frame_id
        msg.pose.covariance[14] = cov
        msg.pose.pose.position.z = depth

        self.depth_pub.publish(msg)


def main(args: Any = None):
    rclpy.init(args=args)
    teleop_node = Bar30Router()
    rclpy.spin(teleop_node)
    teleop_node.destroy_node()
    rclpy.shutdown()
